### ISSUE TITLE
CPIX 문서 URL 최신거로 수정

### ISSUE THREAD

**Issue by jinseok-Noh** [Jason239/pallycon-cpix-client-java#1]
https://github.com/Jason239/pallycon-cpix-client-java/blob/1ef852a057710579d644fd13a7cd49323aec27a1/README.md?plain=1#L123

현재 CPIX 문서는 2.3 버전입니다.
https://dashif-documents.azurewebsites.net/Cpix/master/Cpix.html

**Comment by Jason239** [comment]
수정 반영하였습니다.
