### ISSUE TITLE
TC 내용을 알수 있도록

### ISSUE THREAD

**Issue by jinseok-Noh** [Jason239/pallycon-cpix-client-java#2]
https://github.com/Jason239/pallycon-cpix-client-java/blob/1ef852a057710579d644fd13a7cd49323aec27a1/src/test/java/com/pallycon/cpix/CpixClientTest.java#L41C7-L41C7

주석 또는 `@DisplayName("샘플 소스 테스트")`  등으로 어떤 의미의 테스트 케이스 인지 명시해주는게 좋을것 같습니다.

**Comment by Jason239** [comment]
수정 반영하였습니다.
