### ISSUE TITLE
util import 수정

### ISSUE THREAD

**Issue by jinseok-Noh** [Jason239/pallycon-cpix-client-java#3]
https://github.com/Jason239/pallycon-cpix-client-java/blob/1ef852a057710579d644fd13a7cd49323aec27a1/src/test/java/com/pallycon/cpix/CpixClientTest.java#L94

util import시에는 static 으로 import 하는것이 아니라 `StringUtil.hexStringToByteArray` 으로 쓰고 StringUtil 를 import 하는것이 좋습니다.

**Comment by Jason239** [comment]
수정 반영하였습니다.
