### ISSUE TITLE
XML 파싱 및 생성시 Element create 대신 Object class로 만드는게 직관적입니다.

### ISSUE THREAD

**Issue by jinseok-Noh** [Jason239/pallycon-cpix-client-java#5]
XML 파싱 및 생성시 Element create 대신 Object class로 만드는게 직관적입니다.

현재 개발되어진 이부분은 Java 개발자가 만든게 아닌거 같다라는 느낌을 많이줘서 이건 팀장님과 협의해서 수정할지 말지 결정 하시면 될거 같아요.

이부분 때문에 저희 KMS 서버에서 쓰고 잇는 cpix module은 기존꺼 그대로 써야 될것 같습니다.   지금 상태로는 다른 프로젝트에서 이 소스를 샘플이 아닌 모듈로써 사용하기에는 어렵습니다.

**Comment by Jason239** [comment]
협의해본 결과 아래와 같은 근거로 현재 상태대로 진행하기로 협의 되었습니다.

- [개발 전 사전 협의](https://teaminka.atlassian.net/wiki/spaces/DT/pages/1773994516/CPIX+Client+Functional+Specification?focusedCommentId=1808793601) 시 논의했던 대로, 기존 cpix module과는 원래 다른 목적으로써 별도로 개발, 관리하기로 결정하기도 했고 단순 샘플을 제공하기 위한 목적에 충분히 부합한다고 판단 되었습니다. 다만 추후 이 부분이 계속 문제가 된다면 패치하는 방향으로 진행하고자 합니다.
